<?php
function bulk_image_generator_Fweight() {

    $options = get_option('bulk_image_generator_options'); ?>

<div class="input_container">


    <select class="el-scrollbar__view el-select-dropdown__optionst"
        name="bulk_image_generator_options[bulk_image_generator_Fweight]" required>
        <!---->
        <option class="el-select-dropdown__item"
            <?php if ($options['bulk_image_generator_Fweight'] == '300') echo ' selected="selected"'; ?> value="300">300
        </option>
        <option class="el-select-dropdown__item hover" value="400"
            <?php if ($options['bulk_image_generator_Fweight'] == '400') echo ' selected="selected"'; ?>>400</option>

        <option class="el-select-dropdown__item hover" value="600"
            <?php if ($options['bulk_image_generator_Fweight'] == '600') echo ' selected="selected"'; ?>>600</option>

        <option class="el-select-dropdown__item hover" value="700"
            <?php if ($options['bulk_image_generator_Fweight'] == '700') echo ' selected="selected"'; ?>>700</option>


        <option class="el-select-dropdown__item hover" value="800"
            <?php if ($options['bulk_image_generator_Fweight'] == '800') echo ' selected="selected"'; ?>>800</option>




    </select>
</div>
<?php }


function bulk_image_generator_Fsize() {

    $options = get_option('bulk_image_generator_options'); ?>
<div class="input_container">


    <input type='range' name='bulk_image_generator_options[bulk_image_generator_Fsize]'
        value='<?php echo $options["bulk_image_generator_Fsize"]; ?>' required>
</div>
<?php }



function bulk_image_generator_Fstyle() {

    $options = get_option('bulk_image_generator_options');

?>
<div class="input_container">

    <select class="el-scrollbar__view el-select-dropdown__optionst"
        name="bulk_image_generator_options[bulk_image_generator_Fstyle]" required>
        <!---->
        <option class="el-select-dropdown__item"
            <?php if ($options['bulk_image_generator_Fstyle'] == 'normal') echo ' selected="selected"'; ?>
            value="normal">Normal
        </option>
        <option class="el-select-dropdown__item hover" value="italic"
            <?php if ($options['bulk_image_generator_Fstyle'] == 'italic') echo ' selected="selected"'; ?>>Italic
        </option>

    </select>
</div>
<?php }



function bulk_image_generator_Ffamily() {

    $options = get_option('bulk_image_generator_options');

?>
<div class="input_container">


    <select name="bulk_image_generator_options[bulk_image_generator_FFamily]"
        data="<?php echo $options["bulk_image_generator_FFamily"]; ?>">
        <option class="">Aclonica</option>
        <option class="hover">Arimo</option>
        <option class="">Calligraffitti</option>
        <option class="">Cherry Cream Soda</option>
        <option class="">Chewy</option>
        <option class="">Coming Soon</option>
        <option class="">Cousine</option>
        <option class="">Crafty Girls</option>
        <option class="">Creepster Caps</option>
        <option class="">Crushed</option>
        <option class="">Droid Arabic Kufi</option>
        <option class="">Droid Arabic Naskh</option>
        <option class="">Droid Sans</option>
        <option class="">Droid Sans Ethiopic</option>
        <option class="">Droid Sans Mono</option>
        <option class="">Droid Sans Thai</option>
        <option class="">Droid Serif</option>
        <option class="">Droid Serif Thai</option>
        <option class="">Fontdiner Swanky</option>
        <option class="">Homemade Apple</option>
        <option class="">Irish Grover</option>
        <option class="">Irish Growler</option>
        <option class="">jsMath cmbx10</option>
        <option class="">jsMath cmex10</option>
        <option class="">jsMath cmmi10</option>
        <option class="">jsMath cmr10</option>
        <option class="">jsMath cmsy10</option>
        <option class="">jsMath cmti10</option>
        <option class="">Just Another Hand</option>
        <option class="">Kranky</option>
        <option class="">Luckiest Guy</option>
        <option class="">Maiden Orange</option>
        <option class="">Montez</option>
        <option class="">Mountains of Christmas</option>
        <option class="">Nokora</option>
        <option class="">Noto Sans</option>
        <option class="">Noto Sans Hebrew</option>
        <option class="">Noto Sans Symbols</option>
        <option class="">Noto Sans UI</option>
        <option class="">Noto Serif</option>
        <option class="">Open Sans</option>
        <option class="">Open Sans Condensed</option>
        <option class="">Permanent Marker</option>
        <option class="">Rancho</option>
        <option class="">Redressed</option>
        <option class="">Roboto</option>
        <option class="">Roboto Condensed</option>
        <option class="">Roboto Mono</option>
        <option class="">Roboto Slab</option>
        <option class="">Rochester</option>
        <option class="">Rock Salt</option>
        <option class="">Satisfy</option>
        <option class="">Schoolbell</option>
        <option class="">Slackey</option>
        <option class="">Smokum</option>
        <option class="">Special Elite</option>
        <option class="">Sunshiney</option>
        <option class="">Syncopate</option>
        <option class="">Tinos</option>
        <option class="">Ultra</option>
        <option class="">Unkempt</option>
        <option class="">Walter Turncoat</option>
        <option class="">Yellowtail</option>
        <option class="">ABeeZee</option>
        <option class="">Abel</option>
        <option class="">Abhaya Libre</option>
        <option class="">Abril Fatface</option>
        <option class="">Acme</option>
        <option class="">Actor</option>
        <option class="">Adamina</option>
        <option class="">Advent Pro</option>
        <option class="">Aguafina Script</option>
        <option class="">Akronim</option>
        <option class="">Aladin</option>
        <option class="">Aldrich</option>
        <option class="">Alef</option>
        <option class="">Alegreya</option>
        <option class="">Alegreya Sans</option>
        <option class="">Alegreya Sans SC</option>
        <option class="">Alegreya SC</option>
        <option class="">Alex Brush</option>
        <option class="">Alfa Slab One</option>
        <option class="">Alice</option>
        <option class="">Alike</option>
        <option class="">Alike Angular</option>
        <option class="">Allan</option>
        <option class="">Allerta</option>
        <option class="">Allerta Stencil</option>
        <option class="">Allura</option>
        <option class="">Almendra</option>
        <option class="">Almendra Display</option>
        <option class="">Almendra SC</option>
        <option class="">Amarante</option>
        <option class="">Amaranth</option>
        <option class="">Amatic SC</option>
        <option class="">Amethysta</option>
        <option class="">Amiri</option>
        <option class="">Amita</option>
        <option class="">Anaheim</option>
        <option class="">Andada</option>
        <option class="">Andada SC</option>
        <option class="">Andika</option>
        <option class="">Angkor</option>
        <option class="">Annie Use Your Telescope</option>
        <option class="">Anonymous Pro</option>
        <option class="">Antic</option>
        <option class="">Antic Didone</option>
        <option class="">Antic Slab</option>
        <option class="">Anton</option>
        <option class="">Antonio</option>
        <option class="">Arapey</option>
        <option class="">Arbutus</option>
        <option class="">Arbutus Slab</option>
        <option class="">Architects Daughter</option>
        <option class="">Archivo Black</option>
        <option class="">Archivo Narrow</option>
        <option class="">Arizonia</option>
        <option class="">Armata</option>
        <option class="">Artifika</option>
        <option class="">Arvo</option>
        <option class="">Arya</option>
        <option class="">Asap</option>
        <option class="">Asar</option>
        <option class="">Asset</option>
        <option class="">Astloch</option>
        <option class="">Asul</option>
        <option class="">Atomic Age</option>
        <option class="">Aubrey</option>
        <option class="">Audiowide</option>
        <option class="">Autour One</option>
        <option class="">Average</option>
        <option class="">Average Sans</option>
        <option class="">Averia Gruesa Libre</option>
        <option class="">Averia Libre</option>
        <option class="">Averia Sans Libre</option>
        <option class="">Averia Serif Libre</option>
        <option class="">Bad Script</option>
        <option class="">Balthazar</option>
        <option class="">Bangers</option>
        <option class="">Basic</option>
        <option class="">Battambang</option>
        <option class="">Baumans</option>
        <option class="">Bayon</option>
        <option class="">Belgrano</option>
        <option class="">Belleza</option>
        <option class="">BenchNine</option>
        <option class="">Bentham</option>
        <option class="">Berkshire Swash</option>
        <option class="">Bevan</option>
        <option class="">Bhavuka</option>
        <option class="">Bigelow Rules</option>
        <option class="">Bigshot One</option>
        <option class="">Bilbo</option>
        <option class="">Bilbo Swash Caps</option>
        <option class="">Biryani</option>
        <option class="">Bitter</option>
        <option class="">Black Ops One</option>
        <option class="">Bokor</option>
        <option class="">Bonbon</option>
        <option class="">Boogaloo</option>
        <option class="">Bowlby One</option>
        <option class="">Bowlby One SC</option>
        <option class="">Brawler</option>
        <option class="">Bree Serif</option>
        <option class="">Bruno Ace</option>
        <option class="">Bruno Ace SC</option>
        <option class="">Bubblegum Sans</option>
        <option class="">Bubbler One</option>
        <option class="">Buda</option>
        <option class="">Buenard</option>
        <option class="">Butcherman</option>
        <option class="">Butcherman Caps</option>
        <option class="">Butterfly Kids</option>
        <option class="">Cabin</option>
        <option class="">Cabin Condensed</option>
        <option class="">Cabin Sketch</option>
        <option class="">Caesar Dressing</option>
        <option class="">Cagliostro</option>
        <option class="">Cambay</option>
        <option class="">Cambo</option>
        <option class="">Candal</option>
        <option class="">Cantarell</option>
        <option class="">Cantata One</option>
        <option class="">Cantora One</option>
        <option class="">Capriola</option>
        <option class="">Cardo</option>
        <option class="">Carme</option>
        <option class="">Carrois Gothic</option>
        <option class="">Carrois Gothic SC</option>
        <option class="">Carter One</option>
        <option class="">Catamaran</option>
        <option class="">Caudex</option>
        <option class="">Caveat</option>
        <option class="">Caveat Brush</option>
        <option class="">Cedarville Cursive</option>
        <option class="">Ceviche One</option>
        <option class="">Changa</option>
        <option class="">Changa One</option>
        <option class="">Chango</option>
        <option class="">Chau Philomene One</option>
        <option class="">Chela One</option>
        <option class="">Chelsea Market</option>
        <option class="">Chenla</option>
        <option class="">Cherry Swash</option>
        <option class="">Chicle</option>
        <option class="">Chivo</option>
        <option class="">Chonburi</option>
        <option class="">Cinzel</option>
        <option class="">Cinzel Decorative</option>
        <option class="">Clara</option>
        <option class="">Clicker Script</option>
        <option class="">Coda</option>
        <option class="">Coda Caption</option>
        <option class="">Codystar</option>
        <option class="">Combo</option>
        <option class="">Comfortaa</option>
        <option class="">Concert One</option>
        <option class="">Condiment</option>
        <option class="">Content</option>
        <option class="">Contrail One</option>
        <option class="">Convergence</option>
        <option class="">Cookie</option>
        <option class="">Copse</option>
        <option class="">Corben</option>
        <option class="">Courgette</option>
        <option class="">Coustard</option>
        <option class="">Covered By Your Grace</option>
        <option class="">Creepster</option>
        <option class="">Crete Round</option>
        <option class="">Crimson Text</option>
        <option class="">Croissant One</option>
        <option class="">Cuprum</option>
        <option class="">Cutive</option>
        <option class="">Cutive Mono</option>
        <option class="">Damion</option>
        <option class="">Dancing Script</option>
        <option class="">Dangrek</option>
        <option class="">Dawning of a New Day</option>
        <option class="">Days One</option>
        <option class="">Dekko</option>
        <option class="">Delius</option>
        <option class="">Delius Swash Caps</option>
        <option class="">Delius Unicase</option>
        <option class="">Della Respira</option>
        <option class="">Denk One</option>
        <option class="">Devonshire</option>
        <option class="">Dhurjati</option>
        <option class="">Dhyana</option>
        <option class="">Didact Gothic</option>
        <option class="">Digital Numbers</option>
        <option class="">Dinah</option>
        <option class="">Diplomata</option>
        <option class="">Diplomata SC</option>
        <option class="">Domine</option>
        <option class="">Donegal One</option>
        <option class="">Doppio One</option>
        <option class="">Dorsa</option>
        <option class="">Dosis</option>
        <option class="">Dr Sugiyama</option>
        <option class="">Duru Sans</option>
        <option class="">Dynalight</option>
        <option class="">Eagle Lake</option>
        <option class="">Eater</option>
        <option class="">Eater Caps</option>
        <option class="">EB Garamond</option>
        <option class="">Economica</option>
        <option class="">Eczar</option>
        <option class="">Ek Mukta</option>
        <option class="">Electrolize</option>
        <option class="">Elsie</option>
        <option class="">Elsie Swash Caps</option>
        <option class="">Emblema One</option>
        <option class="">Emilys Candy</option>
        <option class="">Encode Sans</option>
        <option class="">Encode Sans Compressed</option>
        <option class="">Encode Sans Condensed</option>
        <option class="">Encode Sans Narrow</option>
        <option class="">Encode Sans Wide</option>
        <option class="">Engagement</option>
        <option class="">Englebert</option>
        <option class="">Enriqueta</option>
        <option class="">Erica One</option>
        <option class="">Esteban</option>
        <option class="">Euphoria Script</option>
        <option class="">Ewert</option>
        <option class="">Exo</option>
        <option class="">Exo 2</option>
        <option class="">Expletus Sans</option>
        <option class="">Fanwood Text</option>
        <option class="">Fascinate</option>
        <option class="">Fascinate Inline</option>
        <option class="">Faster One</option>
        <option class="">Fasthand</option>
        <option class="">Fauna One</option>
        <option class="">Federant</option>
        <option class="">Federo</option>
        <option class="">Felipa</option>
        <option class="">Fenix</option>
        <option class="">Finger Paint</option>
        <option class="">Fira Mono</option>
        <option class="">Fira Sans</option>
        <option class="">Fjalla One</option>
        <option class="">Fjord One</option>
        <option class="">Flamenco</option>
        <option class="">Flavors</option>
        <option class="">Fondamento</option>
        <option class="">Forum</option>
        <option class="">Francois One</option>
        <option class="">Freckle Face</option>
        <option class="">Fredericka the Great</option>
        <option class="">Fredoka One</option>
        <option class="">Freehand</option>
        <option class="">Fresca</option>
        <option class="">Frijole</option>
        <option class="">Fruktur</option>
        <option class="">Fugaz One</option>
        <option class="">Gabriela</option>
        <option class="">Gafata</option>
        <option class="">Galdeano</option>
        <option class="">Galindo</option>
        <option class="">Gentium Basic</option>
        <option class="">Gentium Book Basic</option>
        <option class="">Geo</option>
        <option class="">Geostar</option>
        <option class="">Geostar Fill</option>
        <option class="">Germania One</option>
        <option class="">GFS Didot</option>
        <option class="">GFS Neohellenic</option>
        <option class="">Gidugu</option>
        <option class="">Gilda Display</option>
        <option class="">Give You Glory</option>
        <option class="">Glass Antiqua</option>
        <option class="">Glegoo</option>
        <option class="">Gloria Hallelujah</option>
        <option class="">Goblin One</option>
        <option class="">Gochi Hand</option>
        <option class="">Gorditas</option>
        <option class="">Goudy Bookletter 1911</option>
        <option class="">Graduate</option>
        <option class="">Grand Hotel</option>
        <option class="">Gravitas One</option>
        <option class="">Great Vibes</option>
        <option class="">Griffy</option>
        <option class="">Gruppo</option>
        <option class="">Gudea</option>
        <option class="">Gurajada</option>
        <option class="">Habibi</option>
        <option class="">Halant</option>
        <option class="">Hammersmith One</option>
        <option class="">Hanalei</option>
        <option class="">Hanalei Fill</option>
        <option class="">Handlee</option>
        <option class="">Hanuman</option>
        <option class="">Happy Monkey</option>
        <option class="">Headland One</option>
        <option class="">Henny Penny</option>
        <option class="">Hermeneus One</option>
        <option class="">Herr Von Muellerhoff</option>
        <option class="">Hind</option>
        <option class="">Hind Jalandhar</option>
        <option class="">Hind Kochi</option>
        <option class="">Hind Madurai</option>
        <option class="">Hind Mysuru</option>
        <option class="">Hind Siliguri</option>
        <option class="">Hind Vadodara</option>
        <option class="">Holtwood One SC</option>
        <option class="">Homenaje</option>
        <option class="">Iceberg</option>
        <option class="">Iceland</option>
        <option class="">IM Fell Double Pica</option>
        <option class="">IM Fell Double Pica SC</option>
        <option class="">IM Fell DW Pica</option>
        <option class="">IM Fell DW Pica SC</option>
        <option class="">IM Fell English</option>
        <option class="">IM Fell English SC</option>
        <option class="">IM Fell French Canon</option>
        <option class="">IM Fell French Canon SC</option>
        <option class="">IM Fell Great Primer</option>
        <option class="">IM Fell Great Primer SC</option>
        <option class="">Imprima</option>
        <option class="">Inconsolata</option>
        <option class="">Inder</option>
        <option class="">Indie Flower</option>
        <option class="">Inika</option>
        <option class="">Inknut Antiqua</option>
        <option class="">Istok Web</option>
        <option class="">Italiana</option>
        <option class="">Italianno</option>
        <option class="">Itim</option>
        <option class="">Jacques Francois</option>
        <option class="">Jacques Francois Shadow</option>
        <option class="">Jaldi</option>
        <option class="">Jim Nightshade</option>
        <option class="">Jockey One</option>
        <option class="">Jolly Lodger</option>
        <option class="">Josefin Sans</option>
        <option class="">Josefin Sans Std Light</option>
        <option class="">Josefin Slab</option>
        <option class="">Joti One</option>
        <option class="">Judson</option>
        <option class="">Julee</option>
        <option class="">Julius Sans One</option>
        <option class="">Junge</option>
        <option class="">Jura</option>
        <option class="">Just Me Again Down Here</option>
        <option class="">Kadwa</option>
        <option class="">Kalam</option>
        <option class="">Kameron</option>
        <option class="">Kanit</option>
        <option class="">Kantumruy</option>
        <option class="">Karla</option>
        <option class="">Karla Tamil Inclined</option>
        <option class="">Karla Tamil Upright</option>
        <option class="">Karma</option>
        <option class="">Kaushan Script</option>
        <option class="">Kavoon</option>
        <option class="">Kdam Thmor</option>
        <option class="">Keania One</option>
        <option class="">Kelly Slab</option>
        <option class="">Kenia</option>
        <option class="">Khand</option>
        <option class="">Khmer</option>
        <option class="">Khula</option>
        <option class="">Kite One</option>
        <option class="">Knewave</option>
        <option class="">Kotta One</option>
        <option class="">Koulen</option>
        <option class="">Kreon</option>
        <option class="">Kristi</option>
        <option class="">Krona One</option>
        <option class="">Kurale</option>
        <option class="">La Belle Aurore</option>
        <option class="">Laila</option>
        <option class="">Lakki Reddy</option>
        <option class="">Lancelot</option>
        <option class="">Lateef</option>
        <option class="">Lato</option>
        <option class="">League Script</option>
        <option class="">Leckerli One</option>
        <option class="">Ledger</option>
        <option class="">Lekton</option>
        <option class="">Lemon</option>
        <option class="">Lemon One</option>
        <option class="">Libre Baskerville</option>
        <option class="">Libre Caslon Text</option>
        <option class="">Life Savers</option>
        <option class="">Lilita One</option>
        <option class="">Lily Script One</option>
        <option class="">Limelight</option>
        <option class="">Linden Hill</option>
        <option class="">Lobster</option>
        <option class="">Lobster Two</option>
        <option class="">Lohit Bengali</option>
        <option class="">Lohit Tamil</option>
        <option class="">Londrina Outline</option>
        <option class="">Londrina Shadow</option>
        <option class="">Londrina Sketch</option>
        <option class="">Londrina Solid</option>
        <option class="">Lora</option>
        <option class="">Loved by the King</option>
        <option class="">Lovers Quarrel</option>
        <option class="">Love Ya Like A Sister</option>
        <option class="">Lusitana</option>
        <option class="">Lustria</option>
        <option class="">Macondo</option>
        <option class="">Macondo Swash Caps</option>
        <option class="">Magra</option>
        <option class="">Mako</option>
        <option class="">Mallanna</option>
        <option class="">Mandali</option>
        <option class="">Marcellus</option>
        <option class="">Marcellus SC</option>
        <option class="">Marck Script</option>
        <option class="">Margarine</option>
        <option class="">Marko One</option>
        <option class="">Marmelad</option>
        <option class="">Martel</option>
        <option class="">Martel Sans</option>
        <option class="">Marvel</option>
        <option class="">Mate</option>
        <option class="">Mate SC</option>
        <option class="">Maven Pro</option>
        <option class="">McLaren</option>
        <option class="">Meddon</option>
        <option class="">MedievalSharp</option>
        <option class="">Medula One</option>
        <option class="">Megrim</option>
        <option class="">Meie Script</option>
        <option class="">Merge One</option>
        <option class="">Merienda</option>
        <option class="">Merienda One</option>
        <option class="">Merriweather</option>
        <option class="">Merriweather Sans</option>
        <option class="">Mervale Script</option>
        <option class="">Metal</option>
        <option class="">Metal Mania</option>
        <option class="">Metamorphous</option>
        <option class="">Metrophobic</option>
        <option class="">Miama</option>
        <option class="">Michroma</option>
        <option class="">Milonga</option>
        <option class="">Miltonian</option>
        <option class="">Miltonian Tattoo</option>
        <option class="">Miniver</option>
        <option class="">Miss Fajardose</option>
        <option class="">Miss Saint Delafield</option>
        <option class="">Modak</option>
        <option class="">Modern Antiqua</option>
        <option class="">Molengo</option>
        <option class="">Molle</option>
        <option class="">Monda</option>
        <option class="">Monofett</option>
        <option class="">Monoton</option>
        <option class="">Monsieur La Doulaise</option>
        <option class="">Montaga</option>
        <option class="">Montserrat</option>
        <option class="">Montserrat Alternates</option>
        <option class="">Montserrat Subrayada</option>
        <option class="">Moul</option>
        <option class="">Moulpali</option>
        <option class="">Mouse Memoirs</option>
        <option class="">Mr Bedford</option>
        <option class="">Mr Bedfort</option>
        <option class="">Mr Dafoe</option>
        <option class="">Mr De Haviland</option>
        <option class="">Mrs Saint Delafield</option>
        <option class="">Mrs Sheppards</option>
        <option class="">Muli</option>
        <option class="">Mystery Quest</option>
        <option class="">Nanum Brush Script</option>
        <option class="">Nanum Gothic</option>
        <option class="">Nanum Gothic Coding</option>
        <option class="">Nanum Myeongjo</option>
        <option class="">Nanum Pen Script</option>
        <option class="">NATS</option>
        <option class="">Neucha</option>
        <option class="">Neuton</option>
        <option class="">New Rocker</option>
        <option class="">News Cycle</option>
        <option class="">Niconne</option>
        <option class="">Nixie One</option>
        <option class="">Nobile</option>
        <option class="">Norican</option>
        <option class="">Nosifer</option>
        <option class="">Nosifer Caps</option>
        <option class="">Nothing You Could Do</option>
        <option class="">Noticia Text</option>
        <option class="">Nova Cut</option>
        <option class="">Nova Flat</option>
        <option class="">Nova Mono</option>
        <option class="">Nova Oval</option>
        <option class="">Nova Round</option>
        <option class="">Nova Script</option>
        <option class="">Nova Slim</option>
        <option class="">Nova Square</option>
        <option class="">NTR</option>
        <option class="">Numans</option>
        <option class="">Nunito</option>
        <option class="">Odor Mean Chey</option>
        <option class="">Offside</option>
        <option class="">OFL Sorts Mill Goudy TT</option>
        <option class="">Oldenburg</option>
        <option class="">Old Standard TT</option>
        <option class="">Oleo Script</option>
        <option class="">Oleo Script Swash Caps</option>
        <option class="">Oranienbaum</option>
        <option class="">Orbitron</option>
        <option class="">Oregano</option>
        <option class="">Orienta</option>
        <option class="">Original Surfer</option>
        <option class="">Oswald</option>
        <option class="">Overlock</option>
        <option class="">Overlock SC</option>
        <option class="">Over the Rainbow</option>
        <option class="">Ovo</option>
        <option class="">Oxygen</option>
        <option class="">Oxygen Mono</option>
        <option class="">Pacifico</option>
        <option class="">Palanquin</option>
        <option class="">Palanquin Dark</option>
        <option class="">Paprika</option>
        <option class="">Parisienne</option>
        <option class="">Passero One</option>
        <option class="">Passion One</option>
        <option class="">Pathway Gothic One</option>
        <option class="">Patrick Hand</option>
        <option class="">Patrick Hand SC</option>
        <option class="">Patua One</option>
        <option class="">Paytone One</option>
        <option class="">Pecita</option>
        <option class="">Peddana</option>
        <option class="">Peralta</option>
        <option class="">Petit Formal Script</option>
        <option class="">Petrona</option>
        <option class="">Phetsarath</option>
        <option class="">Philosopher</option>
        <option class="">Piedra</option>
        <option class="">Pinyon Script</option>
        <option class="">Pirata One</option>
        <option class="">Plaster</option>
        <option class="">Play</option>
        <option class="">Playball</option>
        <option class="">Playfair Display</option>
        <option class="">Playfair Display SC</option>
        <option class="">Podkova</option>
        <option class="">Poetsen One</option>
        <option class="">Poiret One</option>
        <option class="">Poller One</option>
        <option class="">Poly</option>
        <option class="">Pompiere</option>
        <option class="">Ponnala</option>
        <option class="">Pontano Sans</option>
        <option class="">Poppins</option>
        <option class="">Porter Sans Block</option>
        <option class="">Port Lligat Sans</option>
        <option class="">Port Lligat Slab</option>
        <option class="">Pragati Narrow</option>
        <option class="">Prata</option>
        <option class="">Preahvihear</option>
        <option class="">Press Start 2P</option>
        <option class="">Princess Sofia</option>
        <option class="">Prociono</option>
        <option class="">Prosto One</option>
        <option class="">PT Mono</option>
        <option class="">PT Sans</option>
        <option class="">PT Sans Caption</option>
        <option class="">PT Sans Narrow</option>
        <option class="">PT Serif</option>
        <option class="">PT Serif Caption</option>
        <option class="">Puritan</option>
        <option class="">Purple Purse</option>
        <option class="">Quando</option>
        <option class="">Quantico</option>
        <option class="">Quattrocento</option>
        <option class="">Quattrocento Sans</option>
        <option class="">Questrial</option>
        <option class="">Quicksand</option>
        <option class="">Quintessential</option>
        <option class="">Qwigley</option>
        <option class="">Racing Sans One</option>
        <option class="">Radley</option>
        <option class="">Rajdhani</option>
        <option class="">Raleway</option>
        <option class="">Raleway Dots</option>
        <option class="">Ramabhadra</option>
        <option class="">Ramaraja</option>
        <option class="">Rambla</option>
        <option class="">Rammetto One</option>
        <option class="">Ranchers</option>
        <option class="">Ranga</option>
        <option class="">Rationale</option>
        <option class="">Ravi Prakash</option>
        <option class="">Redacted</option>
        <option class="">Redacted Script</option>
        <option class="">Reenie Beanie</option>
        <option class="">Revalia</option>
        <option class="">Rhodium Libre</option>
        <option class="">Ribeye</option>
        <option class="">Ribeye Marrow</option>
        <option class="">Righteous</option>
        <option class="">Risque</option>
        <option class="">Rokkitt</option>
        <option class="">Romanesco</option>
        <option class="">Ropa Sans</option>
        <option class="">Rosario</option>
        <option class="">Rosarivo</option>
        <option class="">Rouge Script</option>
        <option class="">Rozha One</option>
        <option class="">Rubik</option>
        <option class="">Rubik Mono One</option>
        <option class="">Rubik One</option>
        <option class="">Ruda</option>
        <option class="">Rufina</option>
        <option class="">Ruge Boogie</option>
        <option class="">Ruluko</option>
        <option class="">Rum Raisin</option>
        <option class="">Ruslan Display</option>
        <option class="">Russo One</option>
        <option class="">Ruthie</option>
        <option class="">Rye</option>
        <option class="">Sacramento</option>
        <option class="">Sahitya</option>
        <option class="">Sail</option>
        <option class="">Salsa</option>
        <option class="">Sanchez</option>
        <option class="">Sancreek</option>
        <option class="">Sansation</option>
        <option class="">Sansita One</option>
        <option class="">Sarabun</option>
        <option class="">Sarala</option>
        <option class="">Sarina</option>
        <option class="">Sarpanch</option>
        <option class="">Scada</option>
        <option class="">Scheherazade</option>
        <option class="">Seaweed Script</option>
        <option class="">Sedan</option>
        <option class="">Sedan SC</option>
        <option class="">Sevillana</option>
        <option class="">Seymour One</option>
        <option class="">Shadows Into Light</option>
        <option class="">Shadows Into Light Two</option>
        <option class="">Shanti</option>
        <option class="">Share</option>
        <option class="">Share Tech</option>
        <option class="">Share Tech Mono</option>
        <option class="">Shojumaru</option>
        <option class="">Short Stack</option>
        <option class="">Siamreap</option>
        <option class="">Siemreap</option>
        <option class="">Sigmar One</option>
        <option class="">Signika</option>
        <option class="">Signika Negative</option>
        <option class="">Simonetta</option>
        <option class="">Sintony</option>
        <option class="">Sirin Stencil</option>
        <option class="">Sitara</option>
        <option class="">Six Caps</option>
        <option class="">Skranji</option>
        <option class="">Slabo 13px</option>
        <option class="">Slabo 27px</option>
        <option class="">Smythe</option>
        <option class="">Sniglet</option>
        <option class="">Snippet</option>
        <option class="">Snowburst One</option>
        <option class="">Sofadi One</option>
        <option class="">Sofia</option>
        <option class="">Sonsie One</option>
        <option class="">Sorts Mill Goudy</option>
        <option class="">Source Code Pro</option>
        <option class="">Source Sans Pro</option>
        <option class="">Source Serif Pro</option>
        <option class="">Spicy Rice</option>
        <option class="">Spinnaker</option>
        <option class="">Spirax</option>
        <option class="">Squada One</option>
        <option class="">Sree Krushnadevaraya</option>
        <option class="">Sriracha</option>
        <option class="">Stalemate</option>
        <option class="">Stalinist One</option>
        <option class="">Stalin One</option>
        <option class="">Stardos Stencil</option>
        <option class="">Stint Ultra Condensed</option>
        <option class="">Stint Ultra Expanded</option>
        <option class="">Stoke</option>
        <option class="">Strait</option>
        <option class="">Strong</option>
        <option class="">Sue Ellen Francisco</option>
        <option class="">Sumana</option>
        <option class="">Supermercado One</option>
        <option class="">Sura</option>
        <option class="">Suranna</option>
        <option class="">Suravaram</option>
        <option class="">Suwannaphum</option>
        <option class="">Swanky and Moo Moo</option>
        <option class="">Tangerine</option>
        <option class="">Taprom</option>
        <option class="">Tauri</option>
        <option class="">Teko</option>
        <option class="">Telex</option>
        <option class="">Tenali Ramakrishna</option>
        <option class="">Tenor Sans</option>
        <option class="">Terminal Dosis</option>
        <option class="">Terminal Dosis Light</option>
        <option class="">Text Me One</option>
        <option class="">Thabit</option>
        <option class="">The Girl Next Door</option>
        <option class="">Tienne</option>
        <option class="">Tillana</option>
        <option class="">Timmana</option>
        <option class="">Titan One</option>
        <option class="">Titillium Web</option>
        <option class="">Trade Winds</option>
        <option class="">Trocchi</option>
        <option class="">Trochut</option>
        <option class="">Trykker</option>
        <option class="">Tuffy</option>
        <option class="">Tulpen One</option>
        <option class="">Uncial Antiqua</option>
        <option class="">Underdog</option>
        <option class="">Unica One</option>
        <option class="">UnifrakturCook</option>
        <option class="">UnifrakturMaguntia</option>
        <option class="">Unlock</option>
        <option class="">Unna</option>
        <option class="">Vampiro One</option>
        <option class="">Varela</option>
        <option class="">Varela Round</option>
        <option class="">Varta</option>
        <option class="">Vast Shadow</option>
        <option class="">Vesper Libre</option>
        <option class="">Vibur</option>
        <option class="">Vidaloka</option>
        <option class="">Viga</option>
        <option class="">Voces</option>
        <option class="">Volkhov</option>
        <option class="">Vollkorn</option>
        <option class="">Voltaire</option>
        <option class="">VT323</option>
        <option class="">Waiting for the Sunrise</option>
        <option class="">Wallpoet</option>
        <option class="">Warnes</option>
        <option class="">Wellfleet</option>
        <option class="">Wendy One</option>
        <option class="">Wire One</option>
        <option class="">Work Sans</option>
        <option class="">Yanone Kaffeesatz</option>
        <option class="">Yantramanav</option>
        <option class="">Yeseva One</option>
        <option class="">Yesteryear</option>
        <option class="">Zeyada</option>
        <option class="">Ubuntu</option>
        <option class="">Ubuntu Condensed</option>
        <option class="">Ubuntu Mono</option>
        <option class="">Noto Emoji</option>
        <option class="">Noto Kufi Arabic</option>
        <option class="hover">Noto Kufi Arabic Bold</option>
        <option class="">Noto Mono</option>
        <option class="">Noto Naskh Arabic</option>
        <option class="">Noto Naskh Arabic Bold</option>
        <option class="">Noto Nastaliq Urdu</option>
        <option class="">Noto Sans</option>
        <option class="">Noto Sans Armenian</option>
        <option class="">Noto Sans Armenian Bold</option>
        <option class="">Noto Sans Avestan</option>
        <option class="">Noto Sans Balinese</option>
        <option class="">Noto Sans Bamum</option>
        <option class="">Noto Sans Batak</option>
        <option class="">Noto Sans Bengali</option>
        <option class="">Noto Sans Bengali Bold</option>
        <option class="">Noto Sans Bold</option>
        <option class="">Noto Sans Bold Italic</option>
        <option class="">Noto Sans Brahmi</option>
        <option class="">Noto Sans Buginese</option>
        <option class="">Noto Sans Buhid</option>
        <option class="">Noto Sans Canadian Aboriginal</option>
        <option class="">Noto Sans Carian</option>
        <option class="">Noto Sans Cham</option>
        <option class="">Noto Sans Cham Bold</option>
        <option class="">Noto Sans Cherokee</option>
        <option class="">Noto Sans CJK JP Black</option>
        <option class="">Noto Sans CJK JP Bold</option>
        <option class="">Noto Sans CJK JP DemiLight</option>
        <option class="">Noto Sans CJK JP Light</option>
        <option class="">Noto Sans CJK JP Medium</option>
        <option class="">Noto Sans CJK JP Regular</option>
        <option class="">Noto Sans CJK JP Thin</option>
        <option class="">Noto Sans CJK KR Black</option>
        <option class="">Noto Sans CJK KR Bold</option>
        <option class="">Noto Sans CJK KR DemiLight</option>
        <option class="">Noto Sans CJK KR Light</option>
        <option class="">Noto Sans CJK KR Medium</option>
        <option class="">Noto Sans CJK KR Regular</option>
        <option class="">Noto Sans CJK KR Thin</option>
        <option class="">Noto Sans CJK SC Black</option>
        <option class="">Noto Sans CJK SC Bold</option>
        <option class="">Noto Sans CJK SC DemiLight</option>
        <option class="">Noto Sans CJK SC Light</option>
        <option class="">Noto Sans CJK SC Medium</option>
        <option class="">Noto Sans CJK SC Regular</option>
        <option class="">Noto Sans CJK SC Thin</option>
        <option class="">Noto Sans CJK TC Black</option>
        <option class="">Noto Sans CJK TC Bold</option>
        <option class="">Noto Sans CJK TC DemiLight</option>
        <option class="">Noto Sans CJK TC Light</option>
        <option class="">Noto Sans CJK TC Medium</option>
        <option class="">Noto Sans CJK TC Regular</option>
        <option class="">Noto Sans CJK TC Thin</option>
        <option class="">Noto Sans Coptic</option>
        <option class="">Noto Sans Cuneiform</option>
        <option class="">Noto Sans Cypriot</option>
        <option class="">Noto Sans Deseret</option>
        <option class="">Noto Sans Devanagari</option>
        <option class="">Noto Sans Devanagari Bold</option>
        <option class="">Noto Sans Egyptian Hieroglyphs</option>
        <option class="">Noto Sans Ethiopic</option>
        <option class="">Noto Sans Ethiopic Bold</option>
        <option class="">Noto Sans Georgian</option>
        <option class="">Noto Sans Georgian Bold</option>
        <option class="">Noto Sans Glagolitic</option>
        <option class="">Noto Sans Gothic</option>
        <option class="">Noto Sans Gujarati</option>
        <option class="">Noto Sans Gujarati Bold</option>
        <option class="">Noto Sans Gurmukhi</option>
        <option class="">Noto Sans Gurmukhi Bold</option>
        <option class="">Noto Sans Hanunoo</option>
        <option class="">Noto Sans Hebrew</option>
        <option class="">Noto Sans Hebrew Bold</option>
        <option class="">Noto Sans Imperial Aramaic</option>
        <option class="">Noto Sans Inscriptional Pahlavi</option>
        <option class="">Noto Sans Inscriptional Parthian</option>
        <option class="">Noto Sans Italic</option>
        <option class="">Noto Sans Javanese</option>
        <option class="">Noto Sans Kaithi</option>
        <option class="">Noto Sans Kannada</option>
        <option class="">Noto Sans Kannada Bold</option>
        <option class="">Noto Sans Kayah Li</option>
        <option class="">Noto Sans Kharoshthi</option>
        <option class="">Noto Sans Khmer</option>
        <option class="">Noto Sans Khmer Bold</option>
        <option class="">Noto Sans Lao</option>
        <option class="">Noto Sans Lao Bold</option>
        <option class="">Noto Sans Lepcha</option>
        <option class="">Noto Sans Limbu</option>
        <option class="">Noto Sans Linear B</option>
        <option class="">Noto Sans Lisu</option>
        <option class="">Noto Sans Lycian</option>
        <option class="">Noto Sans Lydian</option>
        <option class="">Noto Sans Malayalam</option>
        <option class="">Noto Sans Malayalam Bold</option>
        <option class="">Noto Sans Mandaic</option>
        <option class="">Noto Sans Meetei Mayek</option>
        <option class="">Noto Sans Mongolian</option>
        <option class="">Noto Sans Mono CJK JP Bold</option>
        <option class="">Noto Sans Mono CJK JP Regular</option>
        <option class="">Noto Sans Mono CJK KR Bold</option>
        <option class="">Noto Sans Mono CJK KR Regular</option>
        <option class="">Noto Sans Mono CJK SC Bold</option>
        <option class="">Noto Sans Mono CJK SC Regular</option>
        <option class="">Noto Sans Mono CJK TC Bold</option>
        <option class="">Noto Sans Mono CJK TC Regular</option>
        <option class="">Noto Sans Myanmar</option>
        <option class="">Noto Sans Myanmar Bold</option>
        <option class="">Noto Sans New Tai Lue</option>
        <option class="">Noto Sans NKo</option>
        <option class="">Noto Sans Ogham</option>
        <option class="">Noto Sans Ol Chiki</option>
        <option class="">Noto Sans Old Italic</option>
        <option class="">Noto Sans Old Persian</option>
        <option class="">Noto Sans Old South Arabian</option>
        <option class="">Noto Sans Old Turkic</option>
        <option class="">Noto Sans Oriya</option>
        <option class="">Noto Sans Oriya Bold</option>
        <option class="">Noto Sans Osmanya</option>
        <option class="">Noto Sans Phags Pa</option>
        <option class="">Noto Sans Phoenician</option>
        <option class="">Noto Sans Rejang</option>
        <option class="">Noto Sans Runic</option>
        <option class="">Noto Sans Samaritan</option>
        <option class="">Noto Sans Saurashtra</option>
        <option class="">Noto Sans Shavian</option>
        <option class="">Noto Sans Sinhala</option>
        <option class="">Noto Sans Sinhala Bold</option>
        <option class="">Noto Sans Sundanese</option>
        <option class="">Noto Sans Syloti Nagri</option>
        <option class="">Noto Sans Symbols</option>
        <option class="">Noto Sans Syriac Eastern</option>
        <option class="">Noto Sans Syriac Estrangela</option>
        <option class="">Noto Sans Syriac Western</option>
        <option class="">Noto Sans Tagalog</option>
        <option class="">Noto Sans Tagbanwa</option>
        <option class="">Noto Sans Tai Le</option>
        <option class="">Noto Sans Tai Tham</option>
        <option class="">Noto Sans Tai Viet</option>
        <option class="">Noto Sans Tamil</option>
        <option class="">Noto Sans Tamil Bold</option>
        <option class="">Noto Sans Telugu</option>
        <option class="">Noto Sans Telugu Bold</option>
        <option class="">Noto Sans Thaana</option>
        <option class="">Noto Sans Thaana Bold</option>
        <option class="">Noto Sans Thai</option>
        <option class="">Noto Sans Thai Bold</option>
        <option class="">Noto Sans Tibetan</option>
        <option class="">Noto Sans Tibetan Bold</option>
        <option class="">Noto Sans Tifinagh</option>
        <option class="">Noto Sans Ugaritic</option>
        <option class="">Noto Sans Vai</option>
        <option class="">Noto Sans Yi</option>
        <option class="">Noto Serif</option>
        <option class="">Noto Serif Armenian</option>
        <option class="">Noto Serif Armenian Bold</option>
        <option class="">Noto Serif Bengali</option>
        <option class="">Noto Serif Bengali Bold</option>
        <option class="">Noto Serif Bold</option>
        <option class="">Noto Serif Bold Italic</option>
        <option class="">Noto Serif Devanagari</option>
        <option class="">Noto Serif Devanagari Bold</option>
        <option class="">Noto Serif Georgian</option>
        <option class="">Noto Serif Georgian Bold</option>
        <option class="">Noto Serif Gujarati</option>
        <option class="">Noto Serif Gujarati Bold</option>
        <option class="">Noto Serif Italic</option>
        <option class="">Noto Serif Kannada</option>
        <option class="">Noto Serif Kannada Bold</option>
        <option class="">Noto Serif Lao</option>
        <option class="">Noto Serif Lao Bold</option>
        <option class="">Noto Serif Malayalam</option>
        <option class="">Noto Serif Malayalam Bold</option>
        <option class="">Noto Serif Tamil</option>
        <option class="">Noto Serif Tamil Bold</option>
        <option class="">Noto Serif Telugu</option>
        <option class="">Noto Serif Telugu Bold</option>
        <option class="">Noto Serif Thai</option>
        <option class="">Noto Serif Thai Bold</option>
    </select>
</div>

<?php }